# 강의노트
### OpenCV Filtering

#### 컨볼루션 계산: 특정한 이미지에 커널을 적용해 컨볼루션 계산하여 수행

In [1]:
import cv2
import numpy as np

In [4]:
image = cv2.imread('gray_image.jpg')
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

size = 4 
kernel = np.ones((size, size), np.float32) / (size**2)
print(kernel)

dst = cv2.filter2D(image, -1, kernel)
cv2.imshow('Image', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[0.0625 0.0625 0.0625 0.0625]
 [0.0625 0.0625 0.0625 0.0625]
 [0.0625 0.0625 0.0625 0.0625]
 [0.0625 0.0625 0.0625 0.0625]]
